version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    volumes:
      - .:/workspace
    working_dir: /workspace
    command:
      - /bin/sh
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    volumes:
      - ./images:/usr/local/apache2/htdocs/images
      - ./index.html:/usr/local/apache2/htdocs/index.html
    ports:
      - 8000:80
